# Use postgres/example user/password credentials
# sudo docker-compose (up -d | stop | down)
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432

