

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: example

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    #show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baselineOnMigrate: true

server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO