# Use postgres/example user/password credentials
# sudo docker-compose up -d 
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted

volumes:
  data:

