
server:
  port : 8087

cmis:
  server:
    url: http://localhost:8085

object-type-server:
  url: http://localhost:8083

spring:
  data:
    solr:
      host: http://localhost:8983/solr

logging:
  level:
    root: INFO
